# Generated by Django 3.0.5 on 2020-04-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200411_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='site_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
