# Generated by Django 3.0.3 on 2020-04-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200415_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='site_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
