# Generated by Django 3.0.5 on 2020-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('url', models.URLField(null=True)),
                ('website_image', models.ImageField(null=True, upload_to='img/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('developer', 'Developer'), ('finder', 'Finder')], max_length=25, null=True)),
                ('build_with', models.ManyToManyField(to='projects.Framework')),
            ],
        ),
    ]
